Global:
  debug: false
  use_gpu: true
  epoch_num: &epoch_num 200
  log_smooth_window: 20
  print_batch_step: 20
  save_model_dir: ../data/ckpt/det/OCRv4/cml_student_20250513
  save_epoch_step: 50
  eval_batch_step:
  - 0
  - 2050
  cal_metric_during_train: false
  checkpoints: ../data/ckpt/det/OCRv4/cml_student_20250513/best_accuracy
  pretrained_model:
  save_inference_dir: ../data/ckpt/det/OCRv4/cml_student_20250513/inference
  use_visualdl: false
  infer_img:
  save_res_path: ./checkpoints/det_db/predicts_db.txt
  distributed: true
Architecture:
  name: DistillationModel
  algorithm: Distillation
  model_type: det
  Models:
    Student:
      pretrained: https://paddleocr.bj.bcebos.com/pretrained/PPLCNetV3_x0_75_ocr_det.pdparams
      model_type: det
      algorithm: DB
      Transform: null
      Backbone:
        name: PPLCNetV3
        scale: 0.75
        pretrained: false
        det: true
      Neck:
        name: RSEFPN
        out_channels: 96
        shortcut: true
      Head:
        name: DBHead
        k: 50
    Student2:
      pretrained: https://paddleocr.bj.bcebos.com/pretrained/PPLCNetV3_x0_75_ocr_det.pdparams
      model_type: det
      algorithm: DB
      Transform: null
      Backbone:
        name: PPLCNetV3
        scale: 0.75
        pretrained: true
        det: true
      Neck:
        name: RSEFPN
        out_channels: 96
        shortcut: true
      Head:
        name: DBHead
        k: 50
    Teacher:
      pretrained: https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_det_cml_teacher_pretrained/teacher.pdparams
      freeze_params: true
      return_all_feats: false
      model_type: det
      algorithm: DB
      Backbone:
        name: ResNet_vd
        in_channels: 3
        layers: 50
      Neck:
        name: LKPAN
        out_channels: 256
      Head:
        name: DBHead
        kernel_list:
        - 7
        - 2
        - 2
        k: 50
Loss:
  name: CombinedLoss
  loss_config_list:
  - DistillationDilaDBLoss:
      weight: 1.0
      model_name_pairs:
      - - Student
        - Teacher
      - - Student2
        - Teacher
      key: maps
      balance_loss: true
      main_loss_type: DiceLoss
      alpha: 5
      beta: 10
      ohem_ratio: 3
  - DistillationDMLLoss:
      model_name_pairs:
      - Student
      - Student2
      maps_name: thrink_maps
      weight: 1.0
      key: maps
  - DistillationDBLoss:
      weight: 1.0
      model_name_list:
      - Student
      - Student2
      balance_loss: true
      main_loss_type: DiceLoss
      alpha: 5
      beta: 10
      ohem_ratio: 3
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 2
  regularizer:
    name: L2
    factor: 5.0e-05
PostProcess:
  name: DistillationDBPostProcess
  model_name:
  - Student
  key: head_out
  thresh: 0.1
  box_thresh: 0.1
  max_candidates: 1000
  unclip_ratio: 1.5
Metric:
  name: DistillationMetric
  base_metric_name: DetMetric
  main_indicator: hmean
  key: Student
Train:
  dataset:
    name: SimpleDataSet
    data_dir: ../data/ocr_datasets/det/ocr_det_datasets/
    label_file_list: [
      "../data/ocr_datasets/det/ocr_det_datasets/midu_dataset_1103_train/label_dir_rename_new.txt",
      "../data/ocr_datasets/det/ocr_det_datasets/midu_datasets/Label_train_new_prefix.txt",
      "../data/ocr_datasets/det/ocr_det_datasets/fake_ds_231019/label_dir_rename.txt",
      "../data/ocr_datasets/det/ocr_det_datasets/ctw1500_train/training_new_prefix.txt",
      "../data/ocr_datasets/det/ocr_det_datasets/icdar2015_train/icdar2015_train_new_prefix.txt",
      "../data/ocr_datasets/det/ocr_det_datasets/midu_dataset_vertical_1026_train/label_dir_rename.txt",
      "../data/ocr_datasets/det/ocr_det_datasets/TD_TR_train/train_gt_labels_new_prefix.txt",
      "../data/ocr_datasets/det/ocr_det_datasets/ocr_det_0724_labels/Label_train.txt",
      "../data/ocr_datasets/det/ocr_det_datasets/det_datasets/Label_train_correct.txt",
    ]
    ratio_list: 1.0
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - IaaAugment:
        augmenter_args:
        - type: Fliplr
          args:
            p: 0.5
        - type: Affine
          args:
            rotate:
            - -10
            - 10
        - type: Resize
          args:
            size:
            - 0.5
            - 3
    - AugmentEastRandomCropData:
        size:
        - 640
        - 640
        max_tries: 50
        keep_ratio: true
        limit_side_len: 640
        limit_type: max
        prob: 0.4
    - MakeBorderMap:
        shrink_ratio: 0.4
        thresh_min: 0.3
        thresh_max: 0.7
        total_epoch: *epoch_num
    - MakeShrinkMap:
        shrink_ratio: 0.4
        min_text_size: 8
        total_epoch: *epoch_num
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - threshold_map
        - threshold_mask
        - shrink_map
        - shrink_mask
  loader:
    shuffle: true
    drop_last: false
    batch_size_per_card: 14
    num_workers: 4
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ../data/ocr_datasets/det/ocr_det_datasets/
    label_file_list: [
      "../data/ocr_datasets/det/ocr_det_datasets/midu_dataset_vertical_1026_test/label_dir_rename.txt",
      "../data/ocr_datasets/det/ocr_det_datasets/midu_datasets/Label_val_new_prefix.txt",
      "../data/ocr_datasets/det/ocr_det_datasets/TD_TR_test/test_gt_labels_new_prefix.txt",
      "../data/ocr_datasets/det/ocr_det_datasets/ctw1500_test/test_new_prefix.txt",
      "../data/ocr_datasets/det/ocr_det_datasets/ocr_det_0724_labels/Label_val.txt",
      "../data/ocr_datasets/det/ocr_det_datasets/det_datasets/Label_val_correct.txt",
    ]
    ratio_list: [1.0, 0.5, 1.0, 1.0, 0.8, 0.3]
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - DetResizeForTest:
        limit_side_len: 960
        limit_type: max
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - shape
        - polys
        - ignore_tags
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 1
    num_workers: 2
profiler_options: null
